### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by 0ArturkA** [shekohex/nest-emitter#2]
Hello, how i can import this emitter provider on unit test?
`Nest can't resolve dependencies of the GameController (?, GameService). Please make sure that the argument at index [0] is available in the current context.`
On first argument i have:
`@InjectEventEmitter() private readonly gameEmitter: GameEventEmitter`

May be i can do this using `EVENT_EMITTER_TOKEN` for custom provider, it would be nice then to export it.

It works for me:
```javascript
import { EventEmitter } from 'events';
const EVENT_EMITTER_TOKEN = '__event_emitter__';

{
    provide: EVENT_EMITTER_TOKEN,
    useValue: EventEmitter,
}
```

**Comment by shekohex** [comment]
thank you.
Fixed in `v1.0.1` you can now import `EVENT_EMITTER_TOKEN` from the package.
